from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class QueryRequest(BaseModel):
    query: str = Field(..., description="Citizen's question regarding budget, schemes, or spending", example="How much budget was allocated for healthcare in FY2026?")
    top_k: int = Field(default=4, ge=1, le=20, description="Number of relevant document chunks to retrieve")
    department_filter: Optional[str] = Field(default=None, description="Optional department name to filter document sources", example="Public Health Department")
    language: Optional[str] = Field(default="en", description="Target output language ('en', 'hi', 'mr')", example="en")

class SourceItem(BaseModel):
    document: str = Field(..., description="Name of source document")
    page: int = Field(..., description="Page or record number")
    department: str = Field(..., description="Department associated with the document chunk")
    excerpt: str = Field(..., description="Short text excerpt from the document source")
    verification_status: Optional[str] = Field(default="OFFICIAL_DOCUMENT", description="Trust layer provenance status")

class EvaluationResult(BaseModel):
    judge_score: float = Field(..., description="LLM-as-a-Judge grounding score (0-100)")
    is_grounded: bool = Field(..., description="Factual grounding status")
    issues: List[str] = Field(default_factory=list, description="Detected grounding or numerical inconsistency issues")
    verdict: str = Field(..., description="Evaluation verdict (PASS, WARNING, FAIL)")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="Grounded response generated by RAG LLM pipeline")
    sources: List[SourceItem] = Field(default_factory=list, description="Verifiable sources cited in the response")
    confidence: str = Field(..., description="Confidence level (HIGH, MODERATE, LOW)")
    evaluation: Optional[EvaluationResult] = Field(default=None, description="LLM-as-a-Judge evidence & grounding evaluation")

class IngestionResponse(BaseModel):
    status: str = Field(..., description="Ingestion operation status (e.g. SUCCESS, ERROR)")
    filename: str = Field(..., description="Name of ingested file")
    total_pages: Optional[int] = Field(default=None, description="Total pages processed for PDF documents")
    total_chunks: Optional[int] = Field(default=None, description="Total chunks created")
    total_rows: Optional[int] = Field(default=None, description="Total CSV rows processed")
    embeddings_generated: int = Field(..., description="Total vector embeddings generated and indexed")