import React, { useState } from 'react';
import { 
  ShieldAlert, 
  AlertTriangle, 
  CheckCircle2, 
  Info, 
  Filter, 
  ArrowUpRight, 
  FileSearch, 
  Check, 
  Clock, 
  X,
  ChevronRight,
  ShieldCheck
} from 'lucide-react';
import { aiAlertsData } from '../data/mockData';

export default function AIAlerts() {
  const [alertsList, setAlertsList] = useState(aiAlertsData);
  const [filterSeverity, setFilterSeverity] = useState('All');
  const [filterStatus, setFilterStatus] = useState('All');
  const [activeModalAlert, setActiveModalAlert] = useState(null);

  const handleStatusChange = (alertId, newStatus) => {
    setAlertsList(prev => prev.map(a => a.id === alertId ? { ...a, status: newStatus } : a));
    if (activeModalAlert && activeModalAlert.id === alertId) {
      setActiveModalAlert(prev => ({ ...prev, status: newStatus }));
    }
  };

  const filteredAlerts = alertsList.filter((alert) => {
    const matchesSeverity = filterSeverity === 'All' || alert.severity === filterSeverity;
    const matchesStatus = filterStatus === 'All' || alert.status === filterStatus;
    return matchesSeverity && matchesStatus;
  });

  const criticalCount = alertsList.filter(a => a.severity === 'Critical' && a.status === 'Active').length;
  const warningCount = alertsList.filter(a => a.severity === 'Warning' && a.status === 'Active').length;
  const resolvedCount = alertsList.filter(a => a.status === 'Resolved').length;

  const getSeverityBadge = (severity) => {
    if (severity === 'Critical') {
      return 'bg-rose-500/10 text-rose-400 border-rose-500/30';
    }
    if (severity === 'Warning') {
      return 'bg-amber-500/10 text-amber-400 border-amber-500/30';
    }
    return 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30';
  };

  return (
    <div className="space-y-8 pb-12">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold font-display text-white">
            AI Anomaly & Fraud Monitor
          </h1>
          <p className="text-xs sm:text-sm text-slate-400">
            Algorithmic flags generated by continuous ledger pattern recognition and price benchmarks.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span className="px-3 py-1 rounded-full text-xs font-semibold bg-rose-500/20 text-rose-300 border border-rose-500/30 flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-rose-400 animate-ping" />
            <span>{criticalCount} Critical Unresolved</span>
          </span>
        </div>
      </div>

      {/* Summary KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
        
        <div className="glass-panel rounded-2xl p-5 border border-slate-800 flex items-center justify-between">
          <div>
            <span className="text-xs uppercase font-semibold text-slate-400">Critical Threats</span>
            <h3 className="text-2xl font-bold font-display text-rose-400 mt-1">{criticalCount} Active</h3>
            <p className="text-[11px] text-slate-400 mt-1">Requires immediate treasury action</p>
          </div>
          <div className="p-3 rounded-2xl bg-rose-500/10 border border-rose-500/20 text-rose-400">
            <ShieldAlert className="w-6 h-6" />
          </div>
        </div>

        <div className="glass-panel rounded-2xl p-5 border border-slate-800 flex items-center justify-between">
          <div>
            <span className="text-xs uppercase font-semibold text-slate-400">Warnings & Surges</span>
            <h3 className="text-2xl font-bold font-display text-amber-400 mt-1">{warningCount} Active</h3>
            <p className="text-[11px] text-slate-400 mt-1">Velocity and pattern spikes</p>
          </div>
          <div className="p-3 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-amber-400">
            <AlertTriangle className="w-6 h-6" />
          </div>
        </div>

        <div className="glass-panel rounded-2xl p-5 border border-slate-800 flex items-center justify-between">
          <div>
            <span className="text-xs uppercase font-semibold text-slate-400">Resolved Audit Flags</span>
            <h3 className="text-2xl font-bold font-display text-emerald-400 mt-1">{resolvedCount} Audited</h3>
            <p className="text-[11px] text-slate-400 mt-1">Cleared by city audit board</p>
          </div>
          <div className="p-3 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400">
            <CheckCircle2 className="w-6 h-6" />
          </div>
        </div>

      </div>

      {/* Filter Tabs */}
      <div className="glass-panel rounded-2xl p-4 border border-slate-800 flex flex-wrap items-center justify-between gap-4">
        
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xs font-semibold text-slate-400 mr-2">Severity:</span>
          {['All', 'Critical', 'Warning', 'Info'].map((sev) => (
            <button
              key={sev}
              onClick={() => setFilterSeverity(sev)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all ${
                filterSeverity === sev
                  ? 'bg-cyan-500 text-white shadow-md shadow-cyan-500/20'
                  : 'bg-slate-900 text-slate-400 hover:text-white border border-slate-800'
              }`}
            >
              {sev}
            </button>
          ))}
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xs font-semibold text-slate-400 mr-2">Status:</span>
          {['All', 'Active', 'Under Review', 'Resolved'].map((st) => (
            <button
              key={st}
              onClick={() => setFilterStatus(st)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all ${
                filterStatus === st
                  ? 'bg-indigo-600 text-white shadow-md'
                  : 'bg-slate-900 text-slate-400 hover:text-white border border-slate-800'
              }`}
            >
              {st}
            </button>
          ))}
        </div>

      </div>

      {/* Alert Feed Cards */}
      <div className="space-y-4">
        {filteredAlerts.map((alert) => (
          <div
            key={alert.id}
            className="glass-panel glass-panel-hover rounded-2xl p-5 border border-slate-800 transition-all flex flex-col md:flex-row md:items-center justify-between gap-4"
          >
            <div className="space-y-2 flex-1">
              <div className="flex flex-wrap items-center gap-2">
                <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider border ${getSeverityBadge(alert.severity)}`}>
                  {alert.severity}
                </span>
                <span className="text-xs font-mono text-cyan-400 font-semibold">{alert.id}</span>
                <span className="text-xs text-slate-400">• {alert.department}</span>
                <span className="text-[11px] text-slate-500 ml-auto md:ml-0">{alert.date}</span>
              </div>

              <h3 className="text-base font-bold text-white font-display">{alert.title}</h3>
              <p className="text-xs text-slate-300 leading-relaxed max-w-3xl">{alert.description}</p>
              
              <div className="flex items-center gap-2 text-xs text-slate-400 bg-slate-900/60 p-2.5 rounded-xl border border-slate-800">
                <span className="font-semibold text-cyan-400">AI Recommendation:</span>
                <span className="line-clamp-1">{alert.recommendation}</span>
              </div>
            </div>

            <div className="flex flex-row md:flex-col items-end justify-between md:justify-center gap-3 border-t md:border-t-0 border-slate-800 pt-3 md:pt-0">
              <div className="flex items-center gap-2">
                <span className="text-[10px] text-slate-400">Status:</span>
                <span className={`px-2.5 py-0.5 rounded-full text-xs font-semibold ${
                  alert.status === 'Resolved'
                    ? 'bg-emerald-500/20 text-emerald-400'
                    : alert.status === 'Under Review'
                    ? 'bg-amber-500/20 text-amber-300'
                    : 'bg-rose-500/20 text-rose-400'
                }`}>
                  {alert.status}
                </span>
              </div>

              <div className="flex items-center gap-2">
                {alert.status !== 'Resolved' && (
                  <button
                    onClick={() => handleStatusChange(alert.id, 'Resolved')}
                    className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-emerald-600/20 hover:bg-emerald-600/30 text-emerald-300 border border-emerald-500/40 transition-colors"
                  >
                    Resolve
                  </button>
                )}
                <button
                  onClick={() => setActiveModalAlert(alert)}
                  className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-colors"
                >
                  Audit Details
                </button>
              </div>
            </div>
          </div>
        ))}

        {filteredAlerts.length === 0 && (
          <div className="glass-panel rounded-3xl p-12 text-center text-slate-500">
            No anomaly alerts found matching your selected filters.
          </div>
        )}
      </div>

      {/* Alert Audit Detail Modal */}
      {activeModalAlert && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="glass-panel w-full max-w-xl rounded-3xl p-6 border border-slate-700 bg-slate-900 shadow-2xl space-y-5 animate-in fade-in zoom-in-95">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div className="flex items-center gap-2">
                <ShieldAlert className="w-5 h-5 text-rose-400" />
                <span className="font-display font-bold text-lg text-white">AI Anomaly Audit Record</span>
              </div>
              <button onClick={() => setActiveModalAlert(null)} className="p-1 text-slate-400 hover:text-white">
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-3 text-xs">
              <div className="flex items-center justify-between">
                <span className="font-mono text-cyan-400">{activeModalAlert.id}</span>
                <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase border ${getSeverityBadge(activeModalAlert.severity)}`}>
                  {activeModalAlert.severity} • Risk Score: {activeModalAlert.score}/100
                </span>
              </div>

              <h3 className="text-base font-bold text-white">{activeModalAlert.title}</h3>
              <p className="text-slate-300 leading-relaxed">{activeModalAlert.description}</p>

              <div className="bg-slate-950 p-4 rounded-2xl border border-slate-800 space-y-2">
                <span className="font-semibold text-cyan-400">Algorithmic Recommendation:</span>
                <p className="text-slate-300 leading-relaxed">{activeModalAlert.recommendation}</p>
              </div>

              <div className="grid grid-cols-2 gap-3 text-slate-400 pt-2">
                <div>Department: <strong className="text-slate-200">{activeModalAlert.department}</strong></div>
                <div>Detected On: <strong className="text-slate-200">{activeModalAlert.date}</strong></div>
              </div>
            </div>

            <div className="pt-4 border-t border-slate-800 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleStatusChange(activeModalAlert.id, 'Under Review')}
                  className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-amber-500/20 text-amber-300 hover:bg-amber-500/30"
                >
                  Mark Under Review
                </button>
                <button
                  onClick={() => handleStatusChange(activeModalAlert.id, 'Resolved')}
                  className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-emerald-500/20 text-emerald-300 hover:bg-emerald-500/30"
                >
                  Mark Resolved
                </button>
              </div>

              <button
                onClick={() => setActiveModalAlert(null)}
                className="px-4 py-1.5 rounded-xl text-xs font-semibold bg-slate-800 text-slate-300"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
